### ISSUE TITLE
Disable iOS unnecessary touchscreen actions

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/roar#12]
iOS has a number of default behaviors that create annoyances in our apps:
- double tap zooms
- scrolling is enabled even though we don't want it
- tapping on text sometimes selects the text and opens a "copy" dialogue box (I've only seen this in ROAR-Letter)
We should try to disable all these behaviors to improve gameplay

**Comment by richford** [comment]
@Zio-4, some implementation notes:
- For the text selection issue, use
  ```
  .noselect {
    -webkit-touch-callout: none; /* iOS Safari */
      -webkit-user-select: none; /* Safari */
       -khtml-user-select: none; /* Konqueror HTML */
         -moz-user-select: none; /* Old versions of Firefox */
          -ms-user-select: none; /* Internet Explorer/Edge */
              user-select: none; /* Non-prefixed version, currently
                                    supported by Chrome, Edge, Opera and Firefox */
  }
  ```
  
  See https://stackoverflow.com/a/4407335 for more details. This should be done in all ROAR apps, I think.

- For disabling double-tap zoom, we want to use the CSS `touch-action` property. Set `touch-action: manipulation;` I think. See https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action for more info. We also want to do this in all ROAR apps.

- For scrolling, I think we want it only on the consent screens if they show up. But otherwise, that should also be disabled. But that might also be related to other CSS issues. If no content extends beyond the screen, then it shouldn't scroll anyway, right?
