### ISSUE TITLE
SWR - En Stochastic starting up in Spanish (iPad)

### ISSUE THREAD

**Issue by ctflores** [yeatmanlab/roar#23]
Usually SWR - En starts up in English, but twice now, SWR - En has given me Spanish instructional text (English audio) on the first screen. I am 100% sure I clicked to start SWR - En when this happened. 

This is on iPad with an administration that has both English and Spanish versions assigned, so I'm not sure if it would happen if only one were assigned. It was not consistent, and it seemed to be fixed when I refreshed the screen. 
![IMG_2103](https://github.com/yeatmanlab/roar/assets/35785147/6a2e6ad4-1b2f-490c-9361-558f6ef2a573)

**Comment by richford** [comment]
@Zio-4, I believe this is due to [this line](https://github.com/yeatmanlab/roar-swr/blob/93ee7dacdc40ff4b743ce432eaaf8718dfb96782/src/experiment/config/config.js#L146). Since swr-en does not explicitly pass `lng=en`, it is grabbing the language from `i18next` and I'm betting @ctflores sometimes sets Spanish localization. Even if not, we should make sure that the swr-en task explicitly has `lng=en`
