### ISSUE TITLE
Cleanup of data generated during Clever testing

### ISSUE THREAD

**Issue by tonyamur** [yeatmanlab/roar#52]
There is some data hanging around from when we were doing Clever testing that is associated with actual students, that shows up in new administrations.  I'm going to cut and paste the PID's where data that was generated before 9/11/23 should be deleted.

School: Catalyst Maria Elementary
Administration: IL Catalyst Circle Rock Fall 23-24
- 5b726ec1
- b2f673d9
- 4775fe6c

District: Belmont-Redwood Shores School District
Administration: CA BRSSD Fall 2023
- brs-fox-3f26da30
- brs-fox-f0538653

District: North Tippah Consolidated School District
Administration: MS NTippah Fall 23-24
**These are suspected, double-check the time stamps:**
- 868503d8
- 1e3b6d7f
- 86951324

**Comment by ctflores** [comment]
I am not 100% sure how to label this because I'm not sure where the issue is coming from-- If the students are actually reset in Clever, so they are seeing Assent forms when they log in, and their data in Firebase is going to reflect only the testing they do after 9/11, then it's lower-priority because it is only affecting our view. 

However, if their data that shows up in Firebase and that may show up on their score reports is still reflecting our testing runs, that's a bigger problem.
